//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilety
    {
        public short Id_Biletu { get; set; }
        public Nullable<short> Id_Rezerwacji { get; set; }
        public Nullable<short> Id_Miejsca { get; set; }
        public Nullable<byte> Nr_Miejsca { get; set; }
        public string Id_Uzytkownika { get; set; }
        public string Cena { get; set; }
        public string Rodzaj { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
