//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmy()
        {
            this.Seanse = new HashSet<Seanse>();
        }
    
        public short Id_Filmu { get; set; }
        public string Tytul { get; set; }
        public string Gatunek { get; set; }
        public Nullable<byte> Czas_trwania { get; set; }
        public short Rok_produkcji { get; set; }
        public string Kraj_produkcji { get; set; }
        public string Rezyser { get; set; }
        public string Obsada { get; set; }
        public string Opis { get; set; }
        public string Rodzaj { get; set; }
        public string Ograniczenia { get; set; }
        public string Plakat { get; set; }
        public byte Cena_ulgowy { get; set; }
        public byte Cena_normalny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seanse> Seanse { get; set; }
    }
}
