//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.Models
{
    using System;
    
    public partial class SeanseModelView
    {
        public string Tytul { get; set; }
        public System.DateTime data_i_godzina { get; set; }
        public Nullable<int> miesiac { get; set; }
        public Nullable<int> dzien { get; set; }
        public string godzina { get; set; }
        public Nullable<int> wolne_miejsca { get; set; }
        public string nazwa_dnia { get; set; }
        public short id_seansu { get; set; }
    }
}
