//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seanse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seanse()
        {
            this.Miejsca = new HashSet<Miejsca>();
        }
    
        public short Id_Seansu { get; set; }
        public short Id_Filmu { get; set; }
        public System.DateTime Data_i_godzina { get; set; }
    
        public virtual Filmy Filmy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsca> Miejsca { get; set; }
    }
}
